# Generated by Django 4.2.7 on 2023-11-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avto', '0002_alter_avto_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='avto',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
