# Generated by Django 4.2.7 on 2023-11-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avto', '0003_avto_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avto',
            name='image',
            field=models.ImageField(default='avto_icon.png', upload_to='avto/static/images/'),
        ),
    ]
